package Gui;

import jaco.mp3.player.MP3Player;
import java.awt.Color;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Dalia Vera
 */
public class JugarPartida extends javax.swing.JFrame {

    String n1;
    String n2;
    String n3;
    String n4;
    URL u1;
    URL u2;
    URL u3;
    URL u4;
    MP3Player mp3;

    /**
     * Creates new form JugarPartida
     */
    public JugarPartida(String n1, String n2, String n3, String n4, URL u1, URL u2, URL u3, URL u4) throws MalformedURLException {
        this.n1 = n1;
        this.n2 = n2;
        this.n3 = n3;
        this.n4 = n4;
        this.u1 = u1;
        this.u2 = u2;
        this.u3 = u3;
        this.u4 = u4;

        initComponents();
        setSize(470, 700);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Trivia Music App");
        this.getContentPane().setBackground(Color.white);
        setIconImage(new ImageIcon(getClass().getResource("/img/logo.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() throws MalformedURLException {
        URL[] datos = {u1, u2, u3, u4};
        Random r = new Random();
        URL uriAlAzar = datos[r.nextInt(4)];
        mp3 = new MP3Player(uriAlAzar);
        mp3.play();

        btnOpcion1 = new javax.swing.JButton();
        btnOpcion2 = new javax.swing.JButton();
        btnOpcion3 = new javax.swing.JButton();
        btnOpcion4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnOpcion1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnOpcion1.setText(n1);
        btnOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcion1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnOpcion1);
        btnOpcion1.setBounds(10, 360, 440, 60);

        btnOpcion2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnOpcion2.setText(n2);
        btnOpcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcion2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnOpcion2);
        btnOpcion2.setBounds(10, 430, 440, 60);

        btnOpcion3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnOpcion3.setText(n3);
        btnOpcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcion3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnOpcion3);
        btnOpcion3.setBounds(10, 500, 440, 60);

        btnOpcion4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnOpcion4.setText(n4);
        btnOpcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcion4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnOpcion4);
        btnOpcion4.setBounds(10, 570, 440, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.PNG"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 0, 220, 150);

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(340, 640, 110, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/15218639_1475439615817024_243245446_n.gif"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 140, 120, 200);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo5.jpg.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-10, 0, 490, 690);

        pack();
    }// </editor-fold>                        

    private void btnOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(n1==n2){
        btnOpcion1.setBackground(Color.green);
        dispose();
        FrameGanaste ganaste = new FrameGanaste();
        ganaste.setVisible(true);
        mp3.stop();
        }else{
        btnOpcion1.setBackground(Color.red);
        }
    }

    private void btnOpcion2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        btnOpcion2.setBackground(Color.red);
        FramePerdiste perdiste = new FramePerdiste();
        perdiste.setVisible(true);
        mp3.stop();
    }

    private void btnOpcion3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        btnOpcion3.setBackground(Color.red);
        FramePerdiste perdiste = new FramePerdiste();
        perdiste.setVisible(true);
        mp3.stop();
    }

    private void btnOpcion4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        btnOpcion4.setBackground(Color.red);
        FramePerdiste perdiste = new FramePerdiste();
        perdiste.setVisible(true);
        mp3.stop();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
//        dispose();
//        JugarPartida partida = new JugarPartida();
//        partida.setVisible(true);
        mp3.stop();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws MalformedURLException {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JugarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JugarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JugarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JugarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String a = "a";
                String b = "b";
                String c = "b";
                String d = "b";
                URL e = null;
                URL f = null;
                URL g = null;
                URL h = null;
                try {
                    new JugarPartida(a, b, c, d, e, f, g, h).setVisible(true);
                } catch (MalformedURLException ex) {
                    Logger.getLogger(JugarPartida.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton btnOpcion1;
    private javax.swing.JButton btnOpcion2;
    private javax.swing.JButton btnOpcion3;
    private javax.swing.JButton btnOpcion4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration                   
}
